Dockerfile: Remove extra layer when copying content from builder
crc-org/crc-extension pull request #141
Opened 2023-05-25 08:57 UTC by praveenkumar

2023-05-25 11:15 UTC, gbraad requested changes
This does not solve the request where they expect a single layer
https://github.com/crc-org/crc-extension/issues/138

You will have:
```
COPY --from=builder /opt/app-root/src/...  /extension
COPY --from=builder /opt/app-root/src/dist /extension/dist
```
So still two layers. 

This needs a modifcation to the build process so only a single
folder is needed. Why not doing the folder setup in the `builder`
part, so that:

```
COPY --from=builder /opt/app-root/src/dist/extension /extension
```
would suffice.


Note: At the moment a low(er) priority.

2023-05-30 07:03 UTC, gbraad commented
@evidolob @anjannath I addressed the issues of Praveen's PR. Please have a look

2023-05-30 07:12 UTC, anjannath approved these changes

2023-05-30 07:24 UTC, benoitf commented
thank you guys 🎉

2023-05-30 07:42 UTC, merged