fix: migrate build from rollup to vite
crc-org/crc-extension pull request #225
Opened 2024-06-06 02:06 UTC by dgolovin

Fix #224.

2024-06-06 03:35 UTC, dgolovin commented
There should be no more macOS build issues and build should be much faster.

2024-06-06 07:50 UTC, jeffmaury requested changes

2024-06-06 07:50 UTC, jeffmaury commented on package.json
> +  "dependencies": {
Already in dev dependencies

2024-06-11 06:34 UTC, jeffmaury approved these changes
LGTM

2024-06-11 15:36 UTC, merged